sudo: required
services:
  - docker

before_install:
  - docker build -t rkrongali/docker-react -f Dockerfile.dev .

script:
  - docker run rkrongali/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: docker
  env: "Docker-env"
  bucket_name: "elasticbeansstalk-us-west-2-3001212230987"
  bucker_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
